In [1]:
import pandas as pd
import numpy as np
import datetime
import wikipediaapi

In [76]:
# define class
class telco_wikipedia:
    
    def __init__(self, title):
        self.title = title
    
    def get_page(self):
        wiki = wikipediaapi.Wikipedia(
        language = 'en',
        extract_format = wikipediaapi.ExtractFormat.WIKI
        )
        page = wiki.page(self.title)
        return page

    def get_page_text(self):
        page = self.get_page()
        text = page.text
        return text
    
    def get_page_sections(self):
        page = self.get_page()
        sections = page.sections
        return sections
    
    def get_history(self):
        sections = self.get_page_sections()
        history_list = []
        for item in self.get_page_sections():
            if item.title == 'History':
                for item2 in item.sections:
                    item2_split = item2.text.split(sep = '\n')
                    for item3 in item2_split:
                        if len(item3) > 1:
                            item3_dict = {'Year': item2.title,
                                         'Activity': item3,
                                         'Datetime': datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
                            history_list.append(item3_dict)
        history_df = pd.DataFrame(history_list)
        file_title = self.title.strip().lower().replace(' ','_').replace('(','').replace(')','')
        filename = f"wikipediaapi_{file_title}_{datetime.datetime.now().strftime('%Y%m%d%H%M%S')}.csv"
        history_df.to_csv(filename, index = False)
        return history_df

In [77]:
m1 = telco_wikipedia(title = 'M1 (Singaporean company)')

In [78]:
m1.get_history()

,Year,Activity,Datetime
0,2002,M1 became a publicly listed company in December.,2021-02-07 17:35:31
1,2002,M1 was the first operator in Singapore to laun...,2021-02-07 17:35:31
2,2003,Introduced Singapore's first sports-news servi...,2021-02-07 17:35:31
3,2003,Introduced Singapore's first MMS service for p...,2021-02-07 17:35:31
4,2004,"M1 rebrands itself with a new motto, 1 Life. L...",2021-02-07 17:35:31
...,...,...,...
58,2019,M1 launches new plan - One Plan. You Build It.,2021-02-07 17:35:31
59,2019,M1 rolls out prepaid eSIM card for tourists,2021-02-07 17:35:31
60,2019,M1 collaborates with industry partners to adva...,2021-02-07 17:35:31
61,2019,M1 and UOB collaborate to offer PayNow at all ...,2021-02-07 17:35:31
62,2020,"On 29 April 2020, a joint venture between Star...",2021-02-07 17:35:31

In [79]:
singtel = telco_wikipedia(title = 'Singtel')

In [80]:
singtel.get_history()

,Year,Activity,Datetime
0,1800s,1883: Singapore's phone network was operated b...,2021-02-07 17:35:44
1,1900s,1907: OTEC was replaced by a new Central Telep...,2021-02-07 17:35:44
2,1900s,1955: The Singapore Telephone Board (STB) is i...,2021-02-07 17:35:44
3,1900s,1974: Merger of STB and Telecommunications Aut...,2021-02-07 17:35:44
4,1900s,1982: Merger of the Postal Department with Tel...,2021-02-07 17:35:44
5,1900s,1992: SingTel is incorporated in March (as Tel...,2021-02-07 17:35:44
6,1900s,1992: SingTel introduces the call zone service...,2021-02-07 17:35:44
7,1900s,1997 Singtel was compensated $1.5 billion by t...,2021-02-07 17:35:44
8,2000s,"In 2000, Singtel lost its domestic monopoly in...",2021-02-07 17:35:44
9,2000s,2001: SingTel is awarded a 3G licence in April.,2021-02-07 17:35:44
10,2000s,"In March 2001, Singtel purchased Optus for bet...",2021-02-07 17:35:44
11,2000s,2003: SingTel sells 60% of Singapore Post (Sin...,2021-02-07 17:35:44
12,2000s,2003: SingTel divested its stakes in Yellow Pa...,2021-02-07 17:35:44
13,2000s,2003: SingTel announced that it has appointed ...,2021-02-07 17:35:44
14,2000s,2005: SingTel launches its commercial 3G servi...,2021-02-07 17:35:44
15,2000s,2007: mio TV was launched commercially on 20 J...,2021-02-07 17:35:44
16,2000s,2007: SingTel Generation mio was launched comm...,2021-02-07 17:35:44
17,2000s,2008: SingTel and Apple jointly announced that...,2021-02-07 17:35:44
18,2000s,"In the month of June, SingTel becomes the titl...",2021-02-07 17:35:44
19,2000s,"On 10 July 2009, SingTel launched the iPhone 3...",2021-02-07 17:35:44
20,2011â€“2014,"In May 2011, SingTel announced that they will ...",2021-02-07 17:35:44
21,2011â€“2014,"In November 2011, SingTel launched Singapore's...",2021-02-07 17:35:44
22,2011â€“2014,2012: SingTel acquired mobile advertising tech...,2021-02-07 17:35:44
23,2011â€“2014,2012: SingTel secured broadcast rights for th...,2021-02-07 17:35:44
24,2011â€“2014,"2012: Singtel was fined $300,000 for breaches ...",2021-02-07 17:35:44
25,2011â€“2014,"Since December 2012, SingTel started providing...",2021-02-07 17:35:44
26,2011â€“2014,"Since 1 August 2013, mio TV was officially ren...",2021-02-07 17:35:44
27,2011â€“2014,In 2013 SingTel announced the sale of its enti...,2021-02-07 17:35:44
28,2011â€“2014,"In 2013 SingTel was fined $180,000 for the dis...",2021-02-07 17:35:44
29,2011â€“2014,"In late 2013, Singtel shutdown its Skoob e-boo...",2021-02-07 17:35:44
30,2011â€“2014,In 2014 SingTel was fined $6 million for its B...,2021-02-07 17:35:44
31,2011â€“2014,"In August 2014, SingTel announced it was joini...",2021-02-07 17:35:44
32,2011â€“2014,In 2014 Bharati Airtel became first telecommun...,2021-02-07 17:35:44
33,2015â€“2019,"On 21 January 2015, Singtel launched its new b...",2021-02-07 17:35:44
34,2015â€“2019,"On 19 March 2015, Singtel dismissed all connec...",2021-02-07 17:35:44
35,2015â€“2019,"On 7 April 2015, Singtel revealed it would be ...",2021-02-07 17:35:44
36,2015â€“2019,"On 22 April 2015, the Singtel announced plans ...",2021-02-07 17:35:44
37,2015â€“2019,"In April 2015, Singtel released a new Skype an...",2021-02-07 17:35:44
38,2015â€“2019,"In May 2015, Singtel was issued a 'stern warni...",2021-02-07 17:35:44
39,2015â€“2019,"On 11 April 2017, it was reported that Synack ...",2021-02-07 17:35:44
40,2015â€“2019,"On 18 January 2019, Singtel was listed in the ...",2021-02-07 17:35:44
41,2020-present,"On October 1, 2020, Singtel announced the appo...",2021-02-07 17:35:44
42,2020-present,"On December 4, 2020, it was announced that the...",2021-02-07 17:35:44

In [81]:
starhub = telco_wikipedia(title = 'StarHub')

In [82]:
starhub.get_page_sections

Empty DataFrame
Columns: []
Index: []